### ISSUE TITLE
Impossible to create zip file

### ISSUE THREAD

**Issue by ThomsonVideoNetworks** [OpenSoftwareSolutions/PDFReporter#1]
Hello, I currently have a problem while trying to get the connector for Bonita.
I just downloaded the ZIP from GitHUB and unzipped it, in a bonita-connector-pdfreporter-master folder (which contains LICENSE, pom.xml, README and bonita-connector-pdfreporter-def bonita-connector-pdfreporter-impl folders).

When I execute Maven as indicated (mvn clean install -Dmaven.test.skip=true), I have these errors :

[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[FATAL] Non-resolvable parent POM for org.bonitasoft.connectors:bonita-connector
-pdfreporter:[unknown-version]: Could not transfer artifact org.bonitasoft.conne
ctors:bonita-connectors:pom:1.0.0 from/to OpenSoftwareSolutionsMvn ("https://git
hub.com/OpenSoftwareSolutions/mvn-repo/raw/master/repository/"): Cannot access "
https://github.com/OpenSoftwareSolutions/mvn-repo/raw/master/repository/" with t
ype default using the available connector factories: BasicRepositoryConnectorFac
tory and 'parent.relativePath' points at wrong local POM @ line 6, column 10
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.bonitasoft.connectors:bonita-connector-pdfreporter:[un
known-version](C:UserstarotgDesktopbonita-connector-pdfreporter-masterpom.
xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.bonitasoft.connectors:bonita-conne
ctor-pdfreporter:[unknown-version]: Could not transfer artifact org.bonitasoft.c
onnectors:bonita-connectors:pom:1.0.0 from/to OpenSoftwareSolutionsMvn ("https:/
/github.com/OpenSoftwareSolutions/mvn-repo/raw/master/repository/"): Cannot acce
ss "https://github.com/OpenSoftwareSolutions/mvn-repo/raw/master/repository/" wi
th type default using the available connector factories: BasicRepositoryConnecto
rFactory and 'parent.relativePath' points at wrong local POM @ line 6, column 10
: Cannot access "https://github.com/OpenSoftwareSolutions/mvn-repo/raw/master/re
pository/" using the registered transporter factories: WagonTransporterFactory:
java.util.NoSuchElementException
[ERROR]     role: org.apache.maven.wagon.Wagon
[ERROR]     roleHint: "https
[ERROR]     -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildin
gException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableMo
delException

I've also tried in Administrator, nothing changes...

**Comment by janmagnus** [comment]
see comment on "https://github.com/OpenSoftwareSolutions/bonita-connector-pdfreporter/issues/1"
